version: '3'
services:
  web:
    image: docker-tutorial:latest-alpine
    ports:
     - "80:80"
    depends_on:
      - redis
    networks:
      - webnet
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - webnet
networks: 
  webnet: